name: "[Example Workflow]"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none


jobs:
  # generate a branch name  
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main

  # run various forms of analysis
  codeql_analysis:
    name: "Run CodeQL against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-application-codeql-sast-to-github-security.yml@main
    with:
      application_languages: '["python"]'

  tfsec_analysis:
    name: "Run TFSec against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-to-github-security.yml@main

  docker_build:
    name: "Build Docker images locally"
    needs: [branch_name, codeql_analysis, tfsec_analysis]
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-containers-docker-build.yml@main
    with:
      image_data: '[{"name":"helloworld", "directory":"./service-app"}]'

  # # get a suitable tag
  # create_tag:
  #   name: "Create semvar tag"
  #   needs: [branch_name]
  #   uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semvar-tag.yml@main
  #   with:
  #     branch_name: ${{ needs.branch_name.outputs.raw_branch_name }}
  #   secrets:
  #     source_github_token: ${{ secrets.GITHUB_TOKEN }}




