name: "[Test login Workflow]"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  actions: read
  checks: read
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  statuses: none


jobs:

  login_test:    
    runs-on: 'ubuntu-latest'
    steps:      
      - uses: unfor19/install-aws-cli-action@v1
      - name: Configure AWS Credentials With Assumed Role to Management
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          # management account role
          role-to-assume: arn:aws:iam::311462405659:role/opg-template-repo-ecr
          role-duration-seconds: 900
          role-session-name: OPGExampleWorkflowGithubAction
      